# # # # # # # # # #   Стикеры   # # # # # # # # # #
HELLO_STICKER = "CAACAgIAAxkBAAEEmbFibmcM88jMUQhItJWitmTQeBjFdgACSRYAAsOLeEs1cJYvU2PfdyQE"
SHOP_STICKER = "CAACAgIAAxkBAAEEmbNibmeymHwNw_LwnwmbL7sC4ifSoAACYRYAApUBeUsatN_ZdOmq6CQE"
DEATH_STICKER = "CAACAgIAAxkBAAEEms1ibridDAOemzBFkVXyS8LUmExOVgACRxcAAvuxcEvbmQyQSCSazyQE"
# # # # # # # # # #   Действия   # # # # # # # # # #
RUN = "Сбежать 🏃‍♂"
START_NEW_GAME = "Начать свое приключение 🕹"
SUPPORT = "Поддержка ☎"
SHOP = "Магазин 🏪"
GO_AHEAD = "Пойти вперед 🚶‍♂"
TO_DAMAGE = "Нанести урон 💥"
CONTINUE_GAME = "Продолжить приключение 🕹"
STATISTICS = "Статистика 👤"
MAIN_MENU = "◀ В главное меню ◀"
GAME_MENU = "Игровое меню"
FIGHT_MENU = "Меню боя"
DEATH = "мертв"
NEW_LVL = "новый уровень"
EVENTS_MENU = "Меню ивента"